version: '3.9'
services:
  backend:
    image: 'ioannrove/elastic_beanstalk_example:backend-latest'
    container_name: backend
    restart: unless-stopped
    ports:
      - '1234:8080'

  frontend:
    image: 'ioannrove/elastic_beanstalk_example:frontend-latest'
    container_name: frontend
    restart: unless-stopped
    ports:
      - '1235:80'

  nginx:
    image: 'ioannrove/elastic_beanstalk_example:nginx-latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
